### ISSUE TITLE
Not work for Russian language

### ISSUE THREAD

**Issue by zabihimayvan** [dbpedia-spotlight/dbpedia-spotlight-model#29]
I tried to use spotlight for Russian language. I set the Host to both "http://api.dbpedia-spotlight.org/ru/annotate" and "http://model.dbpedia-spotlight.org/ru/annotate", but non of them works! I received the error below:
`http://api.dbpedia-spotlight.org/ru/annotate
Traceback (most recent call last):
  File "/.../testing.py", line 47, in <module>
    annot = get_annotations(text)
  File "/.../testing.py", line 12, in get_annotations
    confidence=0.4, support=20)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spotlight/__init__.py", line 192, in annotate
    pydict = _post_request(address, payload, filters, headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/spotlight/__init__.py", line 51, in _post_request
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Proxy Error for url: http://api.dbpedia-spotlight.org/ru/annotate
`
I would be appreciative if you help me figure out how to solve it.

**Comment by sandroacoelho** [comment]
Hi @zabihimayvan ,

Our online instances was selected considering DBpedia branches that are online - we have noticed that http://ru.dbpedia.org is not available since 2017 :( 
Btw, you can run it locally using docker

``
docker run -d -p 2227:80 dbpedia/spotlight-russian spotlight.sh
``

and then use it http://localhost:2227/rest/annotate?text=Москва

All the best,

**Comment by zabihimayvan** [comment]
Thank you very much for your response. Actually, I had some problems in setting my local machine as the server when I wanted to use Dbpedia locally. So, I am using it online. Is there any way to have an online address (endpoint) for Russian language?
Thank you in advance :).

**Comment by mgns** [comment]
Setting up spotlight using the docker image is really straightforward. The DOCKER_HOST might be different from localhost when using docker-machine.

**Comment by Gautamshahi** [comment]
Hi zabihimayvan, How did you install it? Do you have Jar file?

**Comment by zabihimayvan** [comment]
Unfortunately, I installed the docker file, but it didn't work for me.
Although I really needed the package for Russian language, I ignored it.
Please let me know if you find any solution.

Thanks,
Mahdieh

**Comment by Gautamshahi** [comment]
Hi,

Thank you.

I am struggling to install it. I will let you know, I am trying to fixed it.

They develop the project for name once the tenure of the project is over
they stop providing the solution.

Then I really don't understand the meaning if open source.

Regards,

**Comment by sandroacoelho** [comment]
Hi @zabihimayvan 

Could you, please, provide us some log to help you? 

@Gautamshahi 

I totally understand your point but is not fair criticize without to provide a solution. I was paying for years a server to keep these endpoints available online and from I remember, you never asked how you could help on it. Remember: You have what you can pay for.

Best,
